// Generated by Framer (78001ac)
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
  addFonts,
  addPropertyControls,
  ControlType,
  cx,
  RichText,
  useActiveVariantCallback,
  useLocaleInfo,
  useVariantState,
  withCSS,
} from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
const cycleOrder = ["eQNOwlFEq", "F1YN6YrUR", "kWIXvpL1k", "IaOxv1jKd"];
const variantClassNames = {
  eQNOwlFEq: "framer-v-1mgj6mm",
  F1YN6YrUR: "framer-v-td77ql",
  IaOxv1jKd: "framer-v-1k21kju",
  kWIXvpL1k: "framer-v-1csl3dn",
};
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0
    ? void 0
    : variants.forEach(
        (variant) => variant && Object.assign(nextOverrides, overrides[variant])
      );
  return nextOverrides;
}
const transitions = {
  default: { damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring" },
};
const Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition =
    value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(
    () => ({ ...config, transition }),
    [JSON.stringify(transition)]
  );
  return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
    value: contextValue,
    children: children,
  });
};
const humanReadableVariantMap = {
  "Phone Open": "IaOxv1jKd",
  Desktop: "eQNOwlFEq",
  Phone: "kWIXvpL1k",
  Tablet: "F1YN6YrUR",
};
const getProps = ({ height, id, width, ...props }) => {
  var _variant, ref;
  return {
    ...props,
    variant:
      (ref =
        (_variant = humanReadableVariantMap[props.variant]) !== null &&
        _variant !== void 0
          ? _variant
          : props.variant) !== null && ref !== void 0
        ? ref
        : "eQNOwlFEq",
  };
};
const createLayoutDependency = (props, variants) =>
  variants.join("-") + props.layoutDependency;
const Component = /*#__PURE__*/ React.forwardRef(function (props, ref) {
  const { activeLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const {
    baseVariant,
    classNames,
    gestureVariant,
    setGestureState,
    setVariant,
    transition,
    variants,
  } = useVariantState({
    cycleOrder,
    defaultVariant: "eQNOwlFEq",
    transitions,
    variant,
    variantClassNames,
  });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } =
    useActiveVariantCallback(baseVariant);
  const onTapw4ac9k = activeVariantCallback(async (...args) => {
    setVariant("IaOxv1jKd");
  });
  const onTap1beiq5i = activeVariantCallback(async (...args) => {
    setVariant("kWIXvpL1k");
  });
  const isDisplayed = () => {
    if (["kWIXvpL1k", "IaOxv1jKd"].includes(baseVariant)) return true;
    return false;
  };
  const isDisplayed1 = () => {
    if (baseVariant === "kWIXvpL1k") return false;
    return true;
  };
  const defaultLayoutId = React.useId();
  return /*#__PURE__*/ _jsx(LayoutGroup, {
    id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
    children: /*#__PURE__*/ _jsx(motion.div, {
      initial: variant,
      animate: variants,
      onHoverStart: () => setGestureState({ isHovered: true }),
      onHoverEnd: () => setGestureState({ isHovered: false }),
      onTapStart: () => setGestureState({ isPressed: true }),
      onTap: () => setGestureState({ isPressed: false }),
      onTapCancel: () => setGestureState({ isPressed: false }),
      className: cx("framer-SPgtG", classNames),
      style: { display: "contents" },
      children: /*#__PURE__*/ _jsx(Transition, {
        value: transition,
        children: /*#__PURE__*/ _jsxs(motion.div, {
          ...restProps,
          className: cx("framer-1mgj6mm", className),
          "data-border": true,
          "data-framer-name": "Desktop",
          layoutDependency: layoutDependency,
          layoutId: "eQNOwlFEq",
          ref: ref,
          style: {
            "--border-bottom-width": "1px",
            "--border-color": "rgba(0, 0, 0, 0.08)",
            "--border-left-width": "0px",
            "--border-right-width": "0px",
            "--border-style": "solid",
            "--border-top-width": "0px",
            backgroundColor: "rgb(255, 255, 255)",
            ...style,
          },
          ...addPropertyOverrides(
            {
              F1YN6YrUR: { "data-framer-name": "Tablet" },
              IaOxv1jKd: { "data-framer-name": "Phone Open" },
              kWIXvpL1k: { "data-framer-name": "Phone" },
            },
            baseVariant,
            gestureVariant
          ),
          children: [
            /*#__PURE__*/ _jsxs(motion.div, {
              className: "framer-16caq4u",
              "data-framer-name": "Title and Icon",
              layoutDependency: layoutDependency,
              layoutId: "kRZFKJX7M",
              children: [
                /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.h2, {
                      style: {
                        "--font-selector": "R0Y7SW50ZXItNzAw",
                        "--framer-font-family":
                          '"Inter", "Inter Placeholder", sans-serif',
                        "--framer-font-weight": "700",
                        "--framer-letter-spacing": "1px",
                        "--framer-line-height": "2em",
                        "--framer-text-alignment": "center",
                        "--framer-text-color": "var(--extracted-1of0zx5)",
                      },
                      children: "FRAMER",
                    }),
                  }),
                  className: "framer-a37c6b",
                  fonts: ["GF;Inter-700"],
                  layoutDependency: layoutDependency,
                  layoutId: "l5CfnN0xP",
                  style: {
                    "--extracted-1of0zx5": "rgb(17, 17, 17)",
                    "--framer-paragraph-spacing": "0px",
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
                isDisplayed() &&
                  /*#__PURE__*/ _jsxs(motion.div, {
                    className: "framer-oeknzv",
                    "data-framer-name": "Icon",
                    layoutDependency: layoutDependency,
                    layoutId: "L4BDcdCJH",
                    ...addPropertyOverrides(
                      {
                        IaOxv1jKd: {
                          "data-highlight": true,
                          onTap: onTap1beiq5i,
                        },
                        kWIXvpL1k: {
                          "data-highlight": true,
                          onTap: onTapw4ac9k,
                        },
                      },
                      baseVariant,
                      gestureVariant
                    ),
                    children: [
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-sdfmnd",
                        "data-framer-name": "Bottom",
                        layoutDependency: layoutDependency,
                        layoutId: "VSsPZsPGf",
                        style: {
                          backgroundColor: "rgb(153, 153, 153)",
                          borderBottomLeftRadius: 10,
                          borderBottomRightRadius: 10,
                          borderTopLeftRadius: 10,
                          borderTopRightRadius: 10,
                          rotate: 0,
                        },
                        variants: { IaOxv1jKd: { rotate: -45 } },
                      }),
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-1d1g6zi",
                        "data-framer-name": "Mid",
                        layoutDependency: layoutDependency,
                        layoutId: "Y3TCFvhxh",
                        style: {
                          backgroundColor: "rgb(153, 153, 153)",
                          borderBottomLeftRadius: 10,
                          borderBottomRightRadius: 10,
                          borderTopLeftRadius: 10,
                          borderTopRightRadius: 10,
                        },
                      }),
                      /*#__PURE__*/ _jsx(motion.div, {
                        className: "framer-18s7ccs",
                        "data-framer-name": "Top",
                        layoutDependency: layoutDependency,
                        layoutId: "BDoiqq0uN",
                        style: {
                          backgroundColor: "rgb(153, 153, 153)",
                          borderBottomLeftRadius: 10,
                          borderBottomRightRadius: 10,
                          borderTopLeftRadius: 10,
                          borderTopRightRadius: 10,
                          rotate: 0,
                        },
                        variants: { IaOxv1jKd: { rotate: 45 } },
                      }),
                    ],
                  }),
              ],
            }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "R0Y7SW50ZXItNTAw",
                      "--framer-font-weight": "500",
                      "--framer-line-height": "1.6em",
                      "--framer-text-alignment": "left",
                      "--framer-text-color": "var(--extracted-r6o4lv)",
                    },
                    children: "About",
                  }),
                }),
                className: "framer-1mqre6v",
                fonts: ["GF;Inter-500"],
                layoutDependency: layoutDependency,
                layoutId: "zDIbzU4R5",
                style: {
                  "--extracted-r6o4lv": "rgb(102, 102, 102)",
                  "--framer-link-hover-text-color": "rgba(153, 153, 153, 0.6)",
                  "--framer-link-text-decoration": "none",
                  "--framer-paragraph-spacing": "0px",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(RichText, {
                __fromCanvasComponent: true,
                children: /*#__PURE__*/ _jsx(React.Fragment, {
                  children: /*#__PURE__*/ _jsx(motion.p, {
                    style: {
                      "--font-selector": "R0Y7SW50ZXItNTAw",
                      "--framer-font-weight": "500",
                      "--framer-line-height": "1.6em",
                      "--framer-text-alignment": "left",
                      "--framer-text-color": "var(--extracted-r6o4lv)",
                    },
                    children: "Contact",
                  }),
                }),
                className: "framer-1vx0j96",
                fonts: ["GF;Inter-500"],
                layoutDependency: layoutDependency,
                layoutId: "bH_SyYLH4",
                style: {
                  "--extracted-r6o4lv": "rgb(102, 102, 102)",
                  "--framer-link-hover-text-color": "rgba(153, 153, 153, 0.6)",
                  "--framer-link-text-decoration": "none",
                  "--framer-paragraph-spacing": "0px",
                },
                verticalAlignment: "top",
                withExternalLayout: true,
              }),
            isDisplayed1() &&
              /*#__PURE__*/ _jsx(motion.div, {
                className: "framer-6jvq5b",
                "data-framer-name": "Button",
                layoutDependency: layoutDependency,
                layoutId: "jmomBmdPi",
                style: {
                  backgroundColor: "rgb(34, 34, 34)",
                  borderBottomLeftRadius: 8,
                  borderBottomRightRadius: 8,
                  borderTopLeftRadius: 8,
                  borderTopRightRadius: 8,
                  boxShadow:
                    "0px 0.7065919983928324px 0.7065919983928324px -0.625px rgba(0, 0, 0, 0.14764), 0px 1.8065619053231785px 1.8065619053231785px -1.25px rgba(0, 0, 0, 0.14398), 0px 3.6217592146567767px 3.6217592146567767px -1.875px rgba(0, 0, 0, 0.13793), 0px 6.8655999097303715px 6.8655999097303715px -2.5px rgba(0, 0, 0, 0.12711), 0px 13.646761411524492px 13.646761411524492px -3.125px rgba(0, 0, 0, 0.10451), 0px 30px 30px -3.75px rgba(0, 0, 0, 0.05)",
                },
                children: /*#__PURE__*/ _jsx(RichText, {
                  __fromCanvasComponent: true,
                  children: /*#__PURE__*/ _jsx(React.Fragment, {
                    children: /*#__PURE__*/ _jsx(motion.p, {
                      style: {
                        "--font-selector": "R0Y7SW50ZXItNjAw",
                        "--framer-font-size": "14px",
                        "--framer-font-weight": "600",
                        "--framer-text-alignment": "center",
                        "--framer-text-color": "var(--extracted-r6o4lv)",
                      },
                      children: "Signup",
                    }),
                  }),
                  className: "framer-1y6caax",
                  fonts: ["GF;Inter-600"],
                  layoutDependency: layoutDependency,
                  layoutId: "yYDuUYKKv",
                  style: {
                    "--extracted-r6o4lv": "rgb(255, 255, 255)",
                    "--framer-link-text-color": "rgb(0, 153, 255)",
                    "--framer-link-text-decoration": "underline",
                    "--framer-paragraph-spacing": "0px",
                  },
                  verticalAlignment: "top",
                  withExternalLayout: true,
                }),
              }),
          ],
        }),
      }),
    }),
  });
});
const css = [
  '.framer-SPgtG [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
  "@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
  ".framer-SPgtG .framer-ebdl1e { display: block; }",
  ".framer-SPgtG .framer-1mgj6mm { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: 80px; justify-content: center; padding: 24px 24px 24px 24px; position: relative; width: 1200px; }",
  ".framer-SPgtG .framer-16caq4u { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; height: 32px; justify-content: space-between; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 1px; }",
  ".framer-SPgtG .framer-a37c6b { flex: none; height: 32px; overflow: hidden; position: relative; white-space: pre; width: auto; }",
  ".framer-SPgtG .framer-oeknzv { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); overflow: hidden; position: relative; width: 32px; }",
  ".framer-SPgtG .framer-sdfmnd { bottom: 7px; flex: none; height: 2px; left: calc(50.00000000000002% - 24px / 2); overflow: hidden; position: absolute; width: 24px; will-change: transform; }",
  ".framer-SPgtG .framer-1d1g6zi { flex: none; height: 2px; left: calc(50.00000000000002% - 24px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 24px; will-change: transform; }",
  ".framer-SPgtG .framer-18s7ccs { flex: none; height: 2px; left: calc(50.00000000000002% - 24px / 2); overflow: hidden; position: absolute; top: 7px; width: 24px; will-change: transform; }",
  ".framer-SPgtG .framer-1mqre6v, .framer-SPgtG .framer-1vx0j96 { flex: none; height: auto; overflow: visible; position: relative; white-space: pre; width: auto; }",
  ".framer-SPgtG .framer-6jvq5b { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: visible; padding: 15px 15px 15px 15px; position: relative; width: min-content; }",
  ".framer-SPgtG .framer-1y6caax { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-SPgtG .framer-1mgj6mm, .framer-SPgtG .framer-6jvq5b { gap: 0px; } .framer-SPgtG .framer-1mgj6mm > * { margin: 0px; margin-left: calc(24px / 2); margin-right: calc(24px / 2); } .framer-SPgtG .framer-1mgj6mm > :first-child, .framer-SPgtG .framer-6jvq5b > :first-child { margin-left: 0px; } .framer-SPgtG .framer-1mgj6mm > :last-child, .framer-SPgtG .framer-6jvq5b > :last-child { margin-right: 0px; } .framer-SPgtG .framer-6jvq5b > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
  ".framer-SPgtG.framer-v-td77ql .framer-1mgj6mm { width: 810px; }",
  ".framer-SPgtG.framer-v-1csl3dn .framer-1mgj6mm { width: 390px; }",
  ".framer-SPgtG.framer-v-1csl3dn .framer-oeknzv, .framer-SPgtG.framer-v-1k21kju .framer-oeknzv { cursor: pointer; }",
  ".framer-SPgtG.framer-v-1k21kju .framer-1mgj6mm { flex-direction: column; height: min-content; padding: 24px 24px 60px 24px; width: 390px; }",
  ".framer-SPgtG.framer-v-1k21kju .framer-16caq4u { flex: none; width: 100%; }",
  ".framer-SPgtG.framer-v-1k21kju .framer-sdfmnd { bottom: 15px; }",
  ".framer-SPgtG.framer-v-1k21kju .framer-1d1g6zi { left: calc(50.00000000000002% - 2px / 2); width: 2px; }",
  ".framer-SPgtG.framer-v-1k21kju .framer-18s7ccs { top: 15px; }",
  ".framer-SPgtG.framer-v-1k21kju .framer-6jvq5b { width: 100%; }",
  "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-SPgtG.framer-v-1k21kju .framer-1mgj6mm { gap: 0px; } .framer-SPgtG.framer-v-1k21kju .framer-1mgj6mm > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-SPgtG.framer-v-1k21kju .framer-1mgj6mm > :first-child { margin-top: 0px; } .framer-SPgtG.framer-v-1k21kju .framer-1mgj6mm > :last-child { margin-bottom: 0px; } }",
];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 80
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"F1YN6YrUR":{"layout":["fixed","fixed"]},"kWIXvpL1k":{"layout":["fixed","fixed"]},"IaOxv1jKd":{"layout":["fixed","auto"]}}}
 */ const FramerG5RcX9QaZ = withCSS(Component, css, "framer-SPgtG");
export default FramerG5RcX9QaZ;
FramerG5RcX9QaZ.displayName = "Navbar";
FramerG5RcX9QaZ.defaultProps = { height: 80, width: 1200 };
addPropertyControls(FramerG5RcX9QaZ, {
  variant: {
    options: ["eQNOwlFEq", "F1YN6YrUR", "kWIXvpL1k", "IaOxv1jKd"],
    optionTitles: ["Desktop", "Tablet", "Phone", "Phone Open"],
    title: "Variant",
    type: ControlType.Enum,
  },
});
addFonts(FramerG5RcX9QaZ, [
  {
    family: "Inter",
    moduleAsset: {
      localModuleIdentifier: "local-module:canvasComponent/G5RcX9QaZ:default",
      url: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    },
    style: "normal",
    url: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
    weight: "700",
  },
  {
    family: "Inter",
    moduleAsset: {
      localModuleIdentifier: "local-module:canvasComponent/G5RcX9QaZ:default",
      url: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf",
    },
    style: "normal",
    url: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf",
    weight: "500",
  },
  {
    family: "Inter",
    moduleAsset: {
      localModuleIdentifier: "local-module:canvasComponent/G5RcX9QaZ:default",
      url: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf",
    },
    style: "normal",
    url: "https://fonts.gstatic.com/s/inter/v12/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYMZhrib2Bg-4.ttf",
    weight: "600",
  },
]);
export const __FramerMetadata__ = {
  exports: {
    default: {
      type: "reactComponent",
      name: "FramerG5RcX9QaZ",
      slots: [],
      annotations: {
        framerCanvasComponentVariantDetails:
          '{"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"F1YN6YrUR":{"layout":["fixed","fixed"]},"kWIXvpL1k":{"layout":["fixed","fixed"]},"IaOxv1jKd":{"layout":["fixed","auto"]}}}',
        framerIntrinsicWidth: "1200",
        framerIntrinsicHeight: "80",
        framerContractVersion: "1",
      },
    },
    Props: { type: "tsType", annotations: { framerContractVersion: "1" } },
    __FramerMetadata__: { type: "variable" },
  },
};
//# sourceMappingURL=./G5RcX9QaZ.map
